SELECT * FROM "MEMBER";

SELECT * FROM REVIEW;

SELECT COUNT(*)
FROM REVIEW
WHERE REVIEW_FL = 'N'

SELECT REVIEW_NO, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_DATE, CONTENT_ID,
	FIRST_IMAGE, MEMBER_NO, PROFILE_IMAGE, MEMBER_NICKNAME, REVIEW_IMAGE_PATH
FROM REVIEW
LEFT JOIN "MEMBER" USING(MEMBER_NO)
LEFT JOIN REVIEW_IMAGE USING(REVIEW_NO)
WHERE REVIEW_FL = 'N'
ORDER BY REVIEW_NO;

SELECT * FROM REVIEW_IMAGE;
/*
BEGIN
	FOR I IN 1..20 LOOP
		INSERT INTO REVIEW
		VALUES(SEQ_REVIEW_NO.NEXTVAL,
		DEFAULT, SEQ_REVIEW_NO.CURRVAL || '번째 리뷰',
		SEQ_REVIEW_NO.CURRVAL || '번 리뷰 내용 입니다. 음식이 맛있고 음식이 맛없고 구경거리가 많고 구경거리가 적고 정말 너무 친절하면서 너무 불친절 했습니다.
		다음에 또 오고 싶고 오고 싶지 않더라구요. 추천 합니다. 추천 안합니다.',
		DEFAULT, 2, 294439, NULL, DEFAULT
		);
	END LOOP;
END;
/

COMMIT;

*/

-- 리뷰 리스트 조회시 필요한 컬럼
-- 리뷰 제목, 리뷰 내용, 작성 날짜, 도움이됨 수, 위치 정보 제목, 
-- 장소 섬네일 이미지 주소, 장소 평점, 위치 정보 리뷰 수, 위치 정보 

SELECT REVIEW_NO, REVIEW_TITLE, REVIEW_CONTENT, TO_CHAR(REVIEW_DATE, 'YYYY"년" MM"월"') REVIEW_DATE, 
	CONTENT_ID,	FIRST_IMAGE, MEMBER_NO, PROFILE_IMAGE, MEMBER_NICKNAME
FROM REVIEW
LEFT JOIN "MEMBER" USING(MEMBER_NO)
WHERE REVIEW_FL = 'N'
AND MEMBER_NO = 1
ORDER BY REVIEW_NO;

SELECT * FROM REVIEW_IMAGE;

SELECT * FROM REVIEW_IMAGE
WHERE REVIEW_NO = 1
ORDER BY REVIEW_IMAGE_NO;

SELECT * FROM FOLLOW;

SELECT * FROM "MEMBER";

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_NAME, PROFILE_IMAGE, 
SUBSTR(MEMBER_ADDRESS, 8, 6) MEMBER_ADDRESS, TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월"') REVIEW_DATE
FROM "MEMBER"

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_NAME, PROFILE_IMAGE, 
SUBSTR(MEMBER_ADDRESS, 8, 6) MEMBER_ADDRESS, TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월"') REVIEW_DATE, 
(SELECT COUNT(*)
FROM REVIEW
WHERE REVIEW_FL = 'N'
AND MEMBER_NO = 2)
+
(SELECT COUNT(*)
FROM TRAVEL
WHERE PRIVATE_FL = 'N'
AND MEMBER_NO = 2)
+
(SELECT COUNT(*)
FROM QUESTION
WHERE BLIND_FL = 'N'
AND MEMBER_NO = 2) TOTAL_POSTING,
(SELECT COUNT(*)
FROM FOLLOW
WHERE MEMBER_NO = 2) TOTAL_FOLLOWER,
(SELECT COUNT(*)
FROM FOLLOW
WHERE FOLLOW_MEMBER_NO = 2) TOTAL_FOLLOWING
FROM MEMBER
WHERE MEMBER_NO = 2

-- 참고용
--INSERT INTO BOARD_IMG
--VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/',
--'20221116105843_00004.gif', '4.gif', 3 , 1000);

SELECT * FROM REVIEW
WHERE MEMBER_NO = 1;

SELECT * FROM REVIEW_IMAGE;

INSERT INTO REVIEW_IMAGE
VALUES
(SEQ_REVIEW_IMAGE_NO.NEXTVAL, 2, '/resources/images/profile/', DEFAULT, 0, 'hills123.jpg', 'hills.jpg');

INSERT INTO REVIEW_IMAGE
VALUES
(SEQ_REVIEW_IMAGE_NO.NEXTVAL, 2, '/resources/images/profile/', DEFAULT, 1, 'alberta123.jpg', 'alberta.jpg');

INSERT INTO REVIEW_IMAGE
VALUES
(SEQ_REVIEW_IMAGE_NO.NEXTVAL, 2, '/resources/images/profile/', DEFAULT, 2, 'avenue123.jpg', 'avenue.jpg');


SELECT * FROM REVIEW_IMAGE
WHERE REVIEW_NO = 3
ORDER BY REVIEW_IMAGE_ORDER;
	
ROLLBACK;
		
COMMIT;

INSERT INTO REVIEW_IMAGE
VALUES
(SEQ_REVIEW_IMAGE_NO.NEXTVAL, 4, '/resources/images/profile/', DEFAULT, 0, 'tree123.jpg', 'tree.jpg');

INSERT INTO REVIEW_IMAGE
VALUES
(SEQ_REVIEW_IMAGE_NO.NEXTVAL, 4, '/resources/images/profile/', DEFAULT, 1, 'thunderstorm123.jpg', 'thunderstorm.jpg');

INSERT INTO REVIEW_IMAGE
VALUES
(SEQ_REVIEW_IMAGE_NO.NEXTVAL, 4, '/resources/images/profile/', DEFAULT, 2, 'road123.jpg', 'road.jpg');