SELECT * FROM "MEMBER";

SELECT * FROM REVIEW;

SELECT REVIEW_NO, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_DATE, CONTENT_ID,
	FIRST_IMAGE, MEMBER_NO, PROFILE_IMAGE, MEMBER_NICKNAME, REVIEW_IMAGE_PATH
FROM REVIEW
JOIN "MEMBER" USING(MEMBER_NO)
JOIN REVIEW_IMAGE USING(REVIEW_NO)
WHERE REVIEW_FL = 'N';

SELECT * FROM REVIEW_IMAGE;